#!/usr/bin/env Rscript
# test_nj_inmemory.R -- validate that the in-memory NJ handoff (nj_inmemory.cpp)
# produces the SAME NJ-R tree as the decenttree CLI does from the identical
# distance matrix. This is the go/no-go gate before using the shim at 249k scale.
#
# Strategy: build a small symmetric distance matrix M (rounded to 4 decimals so the
# CLI's text form and the shim's binary form see byte-identical values -> any tree
# difference is a real handoff bug, not float rounding). Run BOTH paths, compare
# unrooted topology (Robinson-Foulds == 0) and tip sets. Repeat with NAs (to test
# the NaN->median imputation) and at a larger n (to exercise real clustering).
#
# Usage (on the instance, in the repo (tree_building/)):
#   Rscript 1_build_nj_backbone/tests/test_nj_inmemory.R
# (set DTT_DIR if decenttree lives somewhere other than ./decenttree)

suppressWarnings(suppressMessages({
  library(Rcpp)
}))

SCRIPT_DIR <- "1_build_nj_backbone"
DTT_DIR    <- Sys.getenv("DTT_DIR", "decenttree")
DECENTTREE <- file.path(DTT_DIR, "build/decenttree")
stopifnot(dir.exists(DTT_DIR), file.exists(DECENTTREE))

# writer (CLI path) + the in-memory shim (compiled against decenttree headers).
# decenttree_config.h is generated by cmake into the build/ dir, so include both.
Rcpp::sourceCpp(file.path(SCRIPT_DIR, "dtt_phylip_writer.cpp"))
# OpenMP: Linux gcc/clang take -fopenmp directly. Apple clang / Homebrew's
# libomp don't resolve decenttree's OpenMP usage cleanly, so Darwin skips
# OpenMP entirely and compiles single-threaded instead (see run_full_distance.R).
if (Sys.info()[["sysname"]] == "Darwin") {
  omp_cxxflags <- ""
  omp_libs      <- ""
} else {
  omp_cxxflags <- "-fopenmp"
  omp_libs      <- "-fopenmp"
}
Sys.setenv(PKG_CXXFLAGS = paste0("-I", normalizePath(DTT_DIR),
                                 " -I", normalizePath(file.path(DTT_DIR, "build")),
                                 " -O2 ", omp_cxxflags))
Sys.setenv(PKG_LIBS = omp_libs)
Rcpp::sourceCpp(file.path(SCRIPT_DIR, "nj_inmemory.cpp"))

PRECISION <- 6                              # matches the production decenttree CLI default

# NJ from an identical float32 matrix is deterministic, so CLI and shim must emit a
# byte-identical newick. That single check proves both same-topology AND no dropped
# tips -- no ape/phangorn needed (not in this Rlib).
count_tips <- function(path) {
  s <- readChar(path, file.info(path)$size, useBytes = TRUE)
  m <- gregexpr("[(,][^,():]+:", s, perl = TRUE)[[1]]
  if (length(m) == 1 && m[1] == -1) 0L else length(m)
}
# compare newick CONTENT (trim trailing whitespace/newline, which decenttree's two
# write paths format differently but which carry no topological meaning).
read_trim <- function(path) trimws(readChar(path, file.info(path)$size, useBytes = TRUE))
trees_identical <- function(a, b) identical(read_trim(a), read_trim(b))

# --- one case: build M, run both paths, compare ------------------------------
run_case <- function(n, na_frac, nthreads = 4, seed = 1) {
  set.seed(seed)
  # random symmetric distances in [0,1], diag 0, rounded to 4 dp (lossless match)
  M <- matrix(0, n, n)
  ut <- upper.tri(M)
  M[ut] <- round(runif(sum(ut)), 4)
  M <- M + t(M)
  labels <- sprintf("t%05d", seq_len(n))
  dimnames(M) <- list(labels, labels)

  med <- round(median(M[ut]), 4)          # imputed value (4 dp so text==binary)
  if (na_frac > 0) {                        # sprinkle NAs off-diagonal (symmetric)
    k <- floor(sum(ut) * na_frac)
    idx <- sample(which(ut), k)
    M[idx] <- NA
    Mt <- t(M); M[t(ut)] <- Mt[t(ut)]      # mirror NAs to lower triangle
  }

  tmp <- tempfile(); phy <- paste0(tmp, ".phy")
  cli_out <- paste0(tmp, ".cli.nwk"); shim_out <- paste0(tmp, ".shim.nwk")

  # CLI path: write PHYLIP (imputes NA->med, ndigits=4) then decenttree -t NJ-R -f PREC
  write_phylip_lower(M, labels, na_value = med, path = phy, ndigits = 4)
  system2("gzip", c("-f", shQuote(phy)))
  system2(DECENTTREE, c("-in", shQuote(paste0(phy, ".gz")), "-t", "NJ-R",
                        "-nt", nthreads, "-f", PRECISION,
                        "-out", shQuote(cli_out), "-no-banner"),
          stdout = FALSE, stderr = FALSE)

  # in-memory path: hand M straight to RapidNJ (imputes NaN->med internally)
  decenttree_nj_inmem(M, labels, na_value = med, nthreads = nthreads,
                      precision = PRECISION, out_path = shim_out)

  nc <- count_tips(cli_out); ns <- count_tips(shim_out)
  tips_ok <- (nc == n && ns == n)
  same_tree <- trees_identical(cli_out, shim_out)
  ok <- tips_ok && same_tree
  cat(sprintf("  [n=%d, na=%.0f%%] cli_tips=%d shim_tips=%d (want %d)  identical_newick=%s  -> %s\n",
              n, 100 * na_frac, nc, ns, n, same_tree,
              if (ok) "PASS" else "FAIL"))
  ok
}

cat("=== in-memory NJ handoff vs CLI NJ-R (topology identity) ===\n")
results <- c(
  run_case(n = 400,  na_frac = 0.0, seed = 1),
  run_case(n = 400,  na_frac = 0.1, seed = 2),
  run_case(n = 2000, na_frac = 0.0, seed = 3),
  run_case(n = 2000, na_frac = 0.05, seed = 4)
)
np <- sum(results); nt <- length(results)
cat(sprintf("\n%d passed, %d failed\n", np, nt - np))
if (np != nt) quit(status = 1)
