"""Load the merged, placed, dated tree as flat arrays.

The tree_analysis scripts want the tree as five parallel arrays rather than a
Newick string:

    parent   int32   (n_nodes,)  index of each node's parent; -1 at the root
    blen     float64 (n_nodes,)  branch length to the parent
    time     float64 (n_nodes,)  root-to-node distance (the dated tree's node time)
    is_leaf  bool    (n_nodes,)  True for tips
    names    object  (n_nodes,)  node label; "" for unlabelled internal nodes

`load_tree()` produces those directly from support_data/merged_full_placed.nwk,
so nothing extra has to be committed or generated by hand. Parsing 2.4M nodes
takes a few seconds, so the result is cached next to the source file; delete the
cache directory at any time and it will be rebuilt.

A .npz produced by an earlier version of this code still loads, so callers that
pass one keep working.
"""
import os
import sys

import numpy as np

KEYS = ("parent", "blen", "time", "is_leaf", "names")


def parse_newick(text):
    """Iterative Newick parser -> (parent, blen, is_leaf, names).

    Iterative because the tree is far too deep for Python's recursion limit.
    Nodes come out in parse order, which guarantees a parent precedes its
    children -- node_times() relies on that.
    """
    text = text.strip()
    if text.endswith(";"):
        text = text[:-1]

    parent, blen, is_leaf, names = [], [], [], []
    stack = []
    i, n = 0, len(text)

    def add(par):
        parent.append(par)
        blen.append(0.0)
        is_leaf.append(True)
        names.append("")
        return len(parent) - 1

    def read_label(j):
        k = j
        while k < n and text[k] not in "(),:;":
            k += 1
        return text[j:k], k

    def read_len(j):
        if j < n and text[j] == ":":
            k = j + 1
            while k < n and (text[k].isdigit() or text[k] in ".eE+-"):
                k += 1
            try:
                return float(text[j + 1:k]), k
            except ValueError:
                return 0.0, k
        return 0.0, j

    while i < n:
        c = text[i]
        if c == "(":
            node = add(stack[-1] if stack else -1)
            if stack:
                is_leaf[stack[-1]] = False
            stack.append(node)
            i += 1
        elif c == ",":
            i += 1
        elif c == ")":
            cur = stack.pop()
            i += 1
            lab, i = read_label(i)
            if lab:
                names[cur] = lab
            bl, i = read_len(i)
            blen[cur] = bl
        else:
            lab, i = read_label(i)
            bl, i = read_len(i)
            if lab or bl:
                node = add(stack[-1] if stack else -1)
                if stack:
                    is_leaf[stack[-1]] = False
                names[node] = lab
                blen[node] = bl
            else:
                i += 1
    return (np.asarray(parent, dtype=np.int32),
            np.asarray(blen, dtype=np.float64),
            np.asarray(is_leaf, dtype=bool),
            np.asarray(names, dtype=object))


def node_times(parent, blen):
    """Root-to-node distance. Assumes parents precede children."""
    t = np.zeros(parent.shape[0], dtype=np.float64)
    for i in range(parent.shape[0]):
        p = parent[i]
        if p >= 0:
            t[i] = t[p] + blen[i]
    return t


def _cache_path(nwk):
    d = os.path.join(os.path.dirname(os.path.abspath(nwk)), ".tree_cache")
    st = os.stat(nwk)
    return os.path.join(d, f"{os.path.basename(nwk)}.{int(st.st_mtime)}.{st.st_size}.npz")


def load_tree(path, use_cache=True, verbose=True):
    """Return {parent, blen, time, is_leaf, names} for a .nwk (or a legacy .npz)."""
    if path.endswith(".npz"):
        z = np.load(path, allow_pickle=True)
        return {k: z[k] for k in KEYS}

    if use_cache:
        cp = _cache_path(path)
        if os.path.exists(cp):
            z = np.load(cp, allow_pickle=True)
            return {k: z[k] for k in KEYS}

    if verbose:
        sys.stderr.write(f"[tree_io] parsing {os.path.basename(path)} ...\n")
    parent, blen, is_leaf, names = parse_newick(open(path).read())
    out = {"parent": parent, "blen": blen, "time": node_times(parent, blen),
           "is_leaf": is_leaf, "names": names}
    if verbose:
        sys.stderr.write(f"[tree_io]   {parent.size:,} nodes, "
                         f"{int(is_leaf.sum()):,} leaves\n")
    if use_cache:
        try:
            cp = _cache_path(path)
            os.makedirs(os.path.dirname(cp), exist_ok=True)
            np.savez_compressed(cp, **out)
        except OSError:
            pass          # a read-only checkout just re-parses each time
    return out
